# Generated by Django 5.2.10 on 2026-01-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('program_code', models.IntegerField()),
                ('level', models.IntegerField(choices=[(1, 'Undergraduate'), (2, 'Graduate'), (3, 'Doctoral'), (4, 'Exchange'), (5, 'Visitingstudent')])),
            ],
        ),
    ]
