# Generated by Django 5.2.10 on 2026-01-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Present'), (2, 'Absent'), (3, 'Excused')])),
            ],
        ),
    ]
