# Generated by Django 5.2.10 on 2026-01-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_schedule_id',
        ),
        migrations.AddField(
            model_name='class',
            name='class_schedule',
            field=models.ManyToManyField(to='Academic.classschedule'),
        ),
    ]
