# Generated by Django 5.2.10 on 2026-01-27 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program_code',
            field=models.ForeignKey(db_column='program_code_id', on_delete=django.db.models.deletion.CASCADE, to='Academic.program'),
        ),
    ]
