# Generated by Django 5.2.10 on 2026-01-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0002_attendance_class_course_courserequirement_enrollment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
