# Generated by Django 5.2.10 on 2026-01-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0003_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='VOID', max_length=255),
        ),
    ]
