# Generated by Django 5.2.10 on 2026-01-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0004_student_email_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
