# Generated by Django 5.2.10 on 2026-01-27 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0005_alter_student_email_alter_student_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='CourseLevel',
            new_name='courseLevel',
        ),
        migrations.RemoveField(
            model_name='class',
            name='class_code',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='students',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='class',
            name='course_code',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Academic.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='period_offered',
            field=models.IntegerField(choices=[(1, 'Odd'), (2, 'Even'), (3, 'Sp')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='year_offered',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Academic.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Academic.class'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Academic.student'),
        ),
        migrations.AlterField(
            model_name='courserequirement',
            name='course_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_code', to='Academic.course'),
        ),
        migrations.AlterField(
            model_name='courserequirement',
            name='requirement_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_code', to='Academic.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='class_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Academic.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='program_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Academic.program'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ra',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
