# Generated by Django 5.2.10 on 2026-01-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('CourseLevel', models.IntegerField(choices=[(1, 'Undergraduate'), (2, 'Graduate')])),
                ('department', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('offered', models.IntegerField(choices=[(1, 'Odd'), (2, 'Even'), (3, 'Both'), (4, 'Sp')])),
                ('syllabus', models.CharField(max_length=1000)),
            ],
        ),
    ]
