# Generated by Django 6.0.1 on 2026-02-06 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLocation',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('capacity', models.IntegerField()),
                ('building', models.TextField()),
                ('floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('courseLevel', models.IntegerField(choices=[(1, 'Undergraduate'), (2, 'Graduate')])),
                ('department', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('offered', models.IntegerField(choices=[(1, 'Odd'), (2, 'Even'), (3, 'Both'), (4, 'Sp')])),
                ('syllabus', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('start_hour', models.IntegerField()),
                ('lesson_count', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutional.classlocation')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('letter', models.CharField(max_length=1)),
                ('year_offered', models.IntegerField()),
                ('period_offered', models.IntegerField(choices=[(1, 'Odd'), (2, 'Even'), (3, 'Sp')])),
                ('class_schedule', models.ManyToManyField(to='institutional.classschedule')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutional.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='institutional.course')),
                ('requirement_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Requirement', to='institutional.course')),
            ],
        ),
    ]
