# Generated by Django 5.2.10 on 2026-02-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0003_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_schedule',
            field=models.ManyToManyField(related_name='rclass', to='institutional.classschedule'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='location',
            field=models.CharField(max_length=6),
        ),
    ]
