# Generated by Django 6.0.1 on 2026-02-06 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutional', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ra', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(choices=[(1, 'Undergraduate'), (2, 'Graduate'), (3, 'Doctoral'), (4, 'Exchange'), (5, 'Visitingstudent')])),
                ('enrollments', models.ManyToManyField(blank=True, to='institutional.class')),
                ('program_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutional.program')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Present'), (2, 'Absent'), (3, 'Excused')])),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutional.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('academic_class', 'student', 'date')},
            },
        ),
    ]
