# Generated by Django 6.0.1 on 2026-02-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0003_enrollment'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollments',
            field=models.ManyToManyField(blank=True, null=True, to='institutional.class'),
        ),
    ]
