# Generated by Django 5.2.10 on 2026-01-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0002_remove_student_class_schedule_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollments',
            field=models.ManyToManyField(blank=True, to='Academic.class'),
        ),
    ]
