# Generated by Django 6.0.1 on 2026-02-16 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0003_enrollment'),
        ('students', '0002_alter_student_enrollments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Go'), (2, 'Miss'), (3, 'Escused Miss')])),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutional.class')),
                ('signing_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='will_sign', to='students.student')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
