# Generated by Django 6.0.1 on 2026-02-16 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_attendanceintent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceintent',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendanceintent',
            name='signing_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='will_sign', to='students.student'),
        ),
    ]
