# Generated by Django 5.2.10 on 2026-02-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0004_alter_class_class_schedule_and_more'),
        ('students', '0005_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ignore'), (1, 'Present'), (2, 'Absent'), (3, 'Excused')]),
        ),
        migrations.AlterField(
            model_name='attendanceintent',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ignore'), (1, 'Go'), (2, 'Miss'), (3, 'Escused Miss')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollments',
            field=models.ManyToManyField(blank=True, to='institutional.class'),
        ),
    ]
